const MODE = 'DEV' // DEV, STAGE, PROD
const API_TEL = 'https://api.telegram.org/'
const API_BOT = API_TEL + 'bot'
const GET_TEL_FILE = 'file/bot'

const ENVIRONMENTS = {
    PROD: {
        FIREBASE_API_KEY: '',
        FIREBASE_AUTH_DOMAIN: '',
        FIREBASE_DATABASE_URL: '',
        FIREBASE_PROJECT_ID: '',
        BOT_TOKEN: '',      
        ACCOUNT_FILEPATH: './account.json'     
    },
    STAGE: {
        FIREBASE_API_KEY: '',
        FIREBASE_AUTH_DOMAIN: '',
        FIREBASE_DATABASE_URL: '',
        FIREBASE_PROJECT_ID: '',
        BOT_TOKEN: '',
        ACCOUNT_FILEPATH: './account_stage.json'
    },
    DEV: {
        FIREBASE_API_KEY: '',
        FIREBASE_AUTH_DOMAIN: '',
        FIREBASE_DATABASE_URL: '',
        FIREBASE_PROJECT_ID: '',
        BOT_TOKEN: '',        
        ACCOUNT_FILEPATH: './account_dev.json'
    }
}

module.exports = {
    FIREBASE_API_KEY : ENVIRONMENTS[MODE].FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN : ENVIRONMENTS[MODE].FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL : ENVIRONMENTS[MODE].FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID : ENVIRONMENTS[MODE].FIREBASE_PROJECT_ID,
    BOT_TOKEN : ENVIRONMENTS[MODE].BOT_TOKEN,
    ACCOUNT_FILEPATH : ENVIRONMENTS[MODE].ACCOUNT_FILEPATH,
    FILES_ENDPOINT : API_TEL + GET_TEL_FILE + ENVIRONMENTS[MODE].BOT_TOKEN,    
    API_TEL : API_TEL,
    API_BOT : API_BOT
}