const MODE = 'DEV'
const API_TEL = 'https://api.telegram.org/'
const API_BOT = API_TEL + 'bot'
const GET_TEL_FILE = 'file/bot'

// PROD
const PROD_FIREBASE_API_KEY = ''
const PROD_FIREBASE_AUTH_DOMAIN = ''
const PROD_FIREBASE_DATABASE_URL = ''
const PROD_FIREBASE_PROJECT_ID = ''
const PROD_BOT_TOKEN = ''
const PROD_FILES_ENDPOINT = API_TEL + GET_TEL_FILE + PROD_BOT_TOKEN
const PROD_ACCOUNT_FILEPATH = './account.json'

// DEV
const DEV_FIREBASE_API_KEY = ''
const DEV_FIREBASE_AUTH_DOMAIN = ''
const DEV_FIREBASE_DATABASE_URL = ''
const DEV_FIREBASE_PROJECT_ID = ''
const DEV_BOT_TOKEN = ''
const DEV_FILES_ENDPOINT = API_TEL + GET_TEL_FILE + DEV_BOT_TOKEN
const DEV_ACCOUNT_FILEPATH = './account_dev.json'

module.exports = {
    FIREBASE_API_KEY : (MODE === 'PROD') ? PROD_FIREBASE_API_KEY : DEV_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN : (MODE === 'PROD') ? PROD_FIREBASE_AUTH_DOMAIN : DEV_FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL : (MODE === 'PROD') ? PROD_FIREBASE_DATABASE_URL : DEV_FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID : (MODE === 'PROD') ? PROD_FIREBASE_PROJECT_ID : DEV_FIREBASE_PROJECT_ID,
    BOT_TOKEN : (MODE === 'PROD') ? PROD_BOT_TOKEN : DEV_BOT_TOKEN,
    FILES_ENDPOINT : (MODE === 'PROD') ? PROD_FILES_ENDPOINT : DEV_FILES_ENDPOINT,
    ACCOUNT_FILEPATH : (MODE === 'PROD') ? PROD_ACCOUNT_FILEPATH : DEV_ACCOUNT_FILEPATH,
    API_TEL : API_TEL,
    API_BOT : API_BOT
}